# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runiac < Formula
  desc "Run IaC Anywhere with Ease"
  homepage "https://github.com/optum/runiac"
  version "0.0.1-beta1"
  license "Apache2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Optum/runiac/releases/download/v0.0.1-beta1/runiac_0.0.1-beta1_Darwin_x86_64.tar.gz"
    sha256 "57f77874d1257f0220e88c850fcf19ae1307bcbb971ed046f2769fbd74d775ae"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Optum/runiac/releases/download/v0.0.1-beta1/runiac_0.0.1-beta1_Linux_x86_64.tar.gz"
    sha256 "b148b5f1d113c0c4744624f71c0e047c4387f1fa62efaa59e4d07a5ab49e7839"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Optum/runiac/releases/download/v0.0.1-beta1/runiac_0.0.1-beta1_Linux_arm64.tar.gz"
    sha256 "64b93dd1facdf37bffc78d501defab40cfc319c6b5b2f61786b7c0c53144a058"
  end

  def install
    bin.install "runiac"
  end

  test do
    system "#{bin}/runiac version"
  end
end
