# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runiac < Formula
  desc "Run IaC Anywhere with Ease"
  homepage "https://github.com/optum/runiac"
  version "0.0.1-beta4"
  license "Apache2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Optum/runiac/releases/download/v0.0.1-beta4/runiac_0.0.1-beta4_Darwin_x86_64.tar.gz"
    sha256 "a469fcce1841d70ba9029f1b46dcdc53ba2f406fdbb1069dcdf6a0f001ee337b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Optum/runiac/releases/download/v0.0.1-beta4/runiac_0.0.1-beta4_Linux_x86_64.tar.gz"
    sha256 "bc92dca806cb00358cdd0a40d7121091b63c167dd8cc9970f8746a31145ebdc0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Optum/runiac/releases/download/v0.0.1-beta4/runiac_0.0.1-beta4_Linux_arm64.tar.gz"
    sha256 "817d579503d1a89d74e16fc89aac81989cf3e371ed197d873f5a782bfcde917a"
  end

  def install
    bin.install "runiac"
  end

  test do
    system "#{bin}/runiac version"
  end
end
