# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runiac < Formula
  desc "Run IaC Anywhere with Ease"
  homepage "https://runiac.io"
  version "0.0.11"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/runiac/releases/download/v0.0.11/runiac_0.0.11_darwin_x86_64.tar.gz"
      sha256 "d34aa53d872aa3e0ff37ccff00ff295abc92222e34f0ecf23d47700baee34ca2"

      def install
        bin.install "runiac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Optum/runiac/releases/download/v0.0.11/runiac_0.0.11_darwin_arm64.tar.gz"
      sha256 "107bdbc480bbde568c6cd4b391c627ed54e86e78455d0457c1e1e87a2e77d3e7"

      def install
        bin.install "runiac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/runiac/releases/download/v0.0.11/runiac_0.0.11_linux_x86_64.tar.gz"
      sha256 "73243519816ef6a3c7ebf16d5e7d08f45a0c0b60abdd678ffad2a4d4d50ab353"

      def install
        bin.install "runiac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Optum/runiac/releases/download/v0.0.11/runiac_0.0.11_linux_arm64.tar.gz"
      sha256 "ad2ad6bee9ffcc36312caf8729c3e77bd4472f00e62797ef94b78dbb9c701105"

      def install
        bin.install "runiac"
      end
    end
  end

  test do
    system "#{bin}/runiac version"
  end
end
