# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "A cli for common semantic versioning operations"
  homepage "https://github.com/Optum/semver-cli"
  version "2.0.6"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/semver-cli/releases/download/2.0.6/semver.x86_64-apple-darwin.tar.gz"
      sha256 "b5e578a77beb716a0b5ff8f93a26a98beeec088faef596dadbc1390a001e7dd8"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Optum/semver-cli/releases/download/2.0.6/semver.aarch64-apple-darwin.tar.gz"
      sha256 "0a5ea30679decf1923e7fe2bd9ef967a091cf6ac19877169f4e91eaafb2c4b11"

      def install
        bin.install "semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/semver-cli/releases/download/2.0.6/semver.x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ab14735eea60c9532c8afd677ad98e4b1e07be2725719463ffec0eade84a360e"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      raise "Not yet supported"
    end
  end

  test do
    system "#{bin}/semver --version"
  end
end
