# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "A cli for common semantic versioning operations"
  homepage "https://github.com/Optum/semver-cli"
  version "2.0.8"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/semver-cli/releases/download/2.0.8/semver.x86_64-apple-darwin.tar.gz"
      sha256 "2238924ac2c58715bf3f65767c52476602c79e5619389b3670d04c03572cd93b"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Optum/semver-cli/releases/download/2.0.8/semver.aarch64-apple-darwin.tar.gz"
      sha256 "f897ff0447befa6a0cb022dd408150066b39e564bd9a2c210e80472f76bb7896"

      def install
        bin.install "semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/semver-cli/releases/download/2.0.8/semver.x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5e22fd9ec5eb33d62c8f64c6556ceb062dd855e2ea19f1c498eb82dd8de93436"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      raise "Not yet supported"
    end
  end

  test do
    system "#{bin}/semver --version"
  end
end
