# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "A cli for common semantic versioning operations"
  homepage "https://github.com/Optum/semver-cli"
  version "0.1.5"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/semver-cli/releases/download/0.1.5/semver.x86_64-apple-darwin.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Optum/semver-cli/releases/download/0.1.5/semver.aarch64-apple-darwin.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"

      def install
        bin.install "semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Optum/semver-cli/releases/download/0.1.5/semver.x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      raise "Not yet supported"
    end
  end

  test do
    system "#{bin}/semver --version"
  end
end
